cond %{SEND_RESPONSE_HDR_HOOK}
set-header Strict-Transport-Security "max-age=31536000; includeSubDomains"
set-header X-Content-Type-Options "nosniff"
set-header X-Frame-Options "DENY"
set-header Referrer-Policy "strict-origin-when-cross-origin"
