#!/usr/bin/env python3
"""Expand lds.src.yaml (anchors + merge keys, top-level x-* helper keys) into lds.yaml for Envoy's file-based LDS."""
import pathlib
import yaml

src = pathlib.Path(__file__).with_name("lds.src.yaml")
dst = pathlib.Path(__file__).with_name("lds.yaml")
doc = yaml.safe_load(src.read_text())
doc = {k: v for k, v in doc.items() if not k.startswith("x-")}


class Plain(yaml.SafeDumper):           # fully expanded output: no anchors/aliases in the generated file
    def ignore_aliases(self, data):
        return True


tmp = dst.with_suffix(".tmp")   # write + rename: Envoy's watched_directory reacts to MOVED_TO, not to in-place writes
tmp.write_text("# GENERATED by gen.py from lds.src.yaml - do not edit\n" + yaml.dump(doc, Dumper=Plain, sort_keys=False, width=220))
tmp.replace(dst)
print(f"wrote {dst} ({len(doc['resources'])} listeners)")
