#!/usr/bin/env python3
"""Render apisix.yaml from apisix.src.yaml: ${file:certs/x} placeholders become JSON-escaped PEM strings."""
import json
import pathlib
import re

here = pathlib.Path(__file__).resolve().parent
shared = here.parents[1] / "shared"
src = (here / "apisix.src.yaml").read_text()
out = re.sub(r'"\$\{file:([^}]+)\}"', lambda m: json.dumps((shared / m.group(1)).read_text()), src)
tmp = here / "apisix.yaml.tmp"
tmp.write_text("# GENERATED by gen.py from apisix.src.yaml - do not edit\n" + out)
tmp.replace(here / "apisix.yaml")
print("wrote apisix.yaml")
