#!/usr/bin/env python3
"""Expand remap.spec into remap.config. ATS compares the request URL's port (from the Host header, else the listening
port) with the from-URL, so every rule is emitted for the ports clients use. Rules are matched in FILE ORDER (first prefix
match wins), so they are emitted longest-path first and catch-alls last."""
import pathlib
import re

here = pathlib.Path(__file__).resolve().parent
lines = ["# GENERATED by gen.py from remap.spec - do not edit"]
HTTP_PORTS = ["", ":8080", ":18080"]   # "" already means :80
HTTPS_PORTS = ["", ":8443", ":18443"]
specs = [l.strip() for l in (here / "remap.spec").read_text().splitlines() if l.strip() and not l.strip().startswith("#")]
specs.sort(key=lambda l: -len(l.split()[1]))          # longest from-path first: ATS takes the first matching rule
for raw in specs:
    host, path, to, *params = raw.split()
    kind = "redirect" if "@redirect" in params else "map"
    mirror_target = "@mirror-target" in params            # the multiplexer's copies arrive with Host: shadow:8080
    params = [p for p in params if p not in ("@redirect", "@mirror-target")]
    if mirror_target:
        lines.append(f"map http://{host}:8080/ {to}")
        continue
    ptxt = (" " + " ".join(params)) if params else ""
    for port in HTTP_PORTS:
        if kind == "redirect":
            lines.append(f"redirect http://{host}{port}{path} {to}")
        else:
            lines.append(f"map http://{host}{port}{path} {to}{ptxt}")
    if kind == "map" and host in ("app.lab", "a.lab", "b.lab", "mtls.lab", "acme.lab"):
        for port in HTTPS_PORTS + ([":8444", ":18444"] if host == "mtls.lab" else []):
            lines.append(f"map https://{host}{port}{path} {to}{ptxt}")
    if kind == "map" and host == "app.lab" and path == "/":                          # WebSocket requests are remapped as ws:// / wss://
        for port in HTTP_PORTS:
            lines.append(f"map ws://{host}{port}/ ws://app1:8080/")
        for port in HTTPS_PORTS:
            lines.append(f"map wss://{host}{port}/ ws://app1:8080/")
    if kind == "map" and host == "app.lab" and path == "/":                          # catch-alls for localhost / proxy
        for h in ("localhost", "proxy"):
            for port in HTTP_PORTS:
                lines.append(f"map http://{h}{port}/ {to}{ptxt}")
            for port in HTTPS_PORTS:
                lines.append(f"map https://{h}{port}/ {to}{ptxt}")
(here / "remap.config").write_text("\n".join(lines) + "\n")
print(f"wrote remap.config ({len(lines)} rules)")
