#!/usr/bin/env python3
"""Render kong.yml from kong.src.yml: ${file:certs/x} placeholders become the (indented) PEM contents of shared/certs/x.
Kong's declarative config needs certificates inline, and PEMs must not live in a config committed to git."""
import pathlib
import re

here = pathlib.Path(__file__).resolve().parent
shared = here.parents[1] / "shared"
src = (here / "kong.src.yml").read_text()


def repl(m: re.Match) -> str:
    text = (shared / m.group(1)).read_text().strip()
    indent = " " * 6
    return "|\n" + "\n".join(indent + line for line in text.splitlines())


out = re.sub(r"\$\{file:([^}]+)\}", repl, src)
tmp = here / "kong.yml.tmp"
tmp.write_text("# GENERATED by gen.py from kong.src.yml - do not edit\n" + out)
tmp.replace(here / "kong.yml")
print("wrote kong.yml")
